#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Toolchain
CC := C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-gcc.exe
CXX := C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-g++.exe
LD := $(CXX)
AR := C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-ar.exe
OBJCOPY := C:/SysGCC/raspberry/bin/arm-linux-gnueabihf-objcopy.exe

#Additional flags
PREPROCESSOR_MACROS := DEBUG
INCLUDE_DIRS := c:/sysgcc/raspberry/arm-linux-gnueabihf/sysroot/opt/vc/include c:/sysgcc/raspberry/arm-linux-gnueabihf/sysroot/opt/vc/include/interface/vmcs_host/linux c:/sysgcc/raspberry/arm-linux-gnueabihf/sysroot/opt/vc/include/interface/vcos/pthreads c:/sysgcc/raspberry/arm-linux-gnueabihf/sysroot/usr/local/include
LIBRARY_DIRS := c:/sysgcc/raspberry/arm-linux-gnueabihf/sysroot/opt/vc/lib c:/sysgcc/raspberry/arm-linux-gnueabihf/sysroot/usr/local/lib
LIBRARY_NAMES := GLESv2 EGL bcm_host wiringPi pthread jpeg shapes boost_thread boost_system boost_chrono boost_date_time boost_filesystem config++ ws2811
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O0 -std=c++0x -Wno-write-strings
CXXFLAGS := -ggdb -ffunction-sections -O0 -std=c++0x -Wno-write-strings
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
IS_LINUX_PROJECT := 1
